name: Python CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, closed]

  workflow_dispatch:

env:
  GITHUB_SHA: ${{ github.sha }}
  SHORT_SHA: $(echo $GITHUB_SHA | cut -c1-7)
  IMAGE_TAG: ${{ github.event.repository.name }}:$(echo $GITHUB_SHA | cut -c1-7)
  IMAGE_TAG_GITHUB: ghcr.io/${{ github.repository }}:${{ github.sha }}
  THRESHOLD: 90.0

jobs:
  DockerBuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setting Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          no-cache: true
          tags: ${{ env.IMAGE_TAG_GITHUB }}

  UnitTest:
    runs-on: ubuntu-latest
    needs: DockerBuild
    steps:
      - name: Login GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Image Docker
        run: docker pull ${{ env.IMAGE_TAG_GITHUB }}

      - name: test
        run: docker run --privileged --rm ${{ env.IMAGE_TAG_GITHUB }} sh -c "make test"

  deploy:
    runs-on: ubuntu-latest
    # needs: DockerBuild
    needs: UnitTest
    permissions:
      contents: read
      packages: write
    outputs:
      image: ${{ steps.meta.outputs.image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        id: build-image
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}:${{ env.SHORT_SHA }}
        run: |
          docker build . -t ${{ env.IMAGE_TAG }}
          docker tag ${{ env.IMAGE_TAG }}  ${{ env.ECR_REPOSITORY }}
          docker push ${{ env.ECR_REPOSITORY }}

      - name: Update kubeconfig
        run: |
          CLUSTER_NAME=$(aws eks list-clusters --region ${{ secrets.AWS_REGION }} --query "clusters[0]" --output text)
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name $CLUSTER_NAME

      - name: Install moreutils (for sponge)
        run: sudo apt install moreutils

      - name: Deploy to Kubernetes
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}:${{ env.SHORT_SHA }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          SOAT_SECRET_KEY: ${{ secrets.SOAT_SECRET_KEY }}
        run: |
          export K8S_IMAGE_TAG=${{ env.ECR_REPOSITORY }}
          export REPOSITORY_NAME=${{ env.REPOSITORY_NAME }}
          export SOAT_SECRET_KEY=${{ env.SOAT_SECRET_KEY }}
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
          export PROCESSING_API_URL=${{ secrets.PROCESSING_API_URL }}
          export RESULT_API_URL=${{ secrets.RESULT_API_URL }}
          export BUCKET=${{ secrets.BUCKET }}
          export QUEUE_URL=${{ secrets.QUEUE_URL }}
          export AWS_REGION=${{ secrets.AWS_REGION }}


          envsubst < infra/namespace.yml | sponge infra/namespace.yml
          envsubst < infra/secrets/hack-video-worker.yml | sponge infra/secrets/hack-video-worker.yml
          envsubst < infra/configmaps/hack-video-worker.yml | sponge infra/configmaps/hack-video-worker.yml
          envsubst < infra/deployments/hack-video-worker.yml | sponge infra/deployments/hack-video-worker.yml

          kubectl apply -k infra/
          kubectl rollout status deployment/hack-video-worker -n hack-video-worker
